openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:5678/api-docs/#/default/post_users_login
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
